spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/DEV
    username: rdapp
    password: rdapp
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
      pool-name: HikariPoolRD
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create

